# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://StutuS.github.io
date_format: "ordinal"
title: 灵魂的独白
subtitle: "一切为了什么"
description: "张涛的个人空间"
keywords: 灵魂的独白, Tao Zhang, tzlogin, zhangtao
timezone: Asia/kaifeng
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Tao Zhang
#organization: zkh360.com
#organization_url: http://www.zkh360.com
github_username: StutuS
location: Kaifeng, China
email: 2645954484@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: StututS/StutuS.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalkhttps://disqus.com
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# 
disqus:https://imsun.net/posts/gitment-introduction/
    username: 
# 
gitment:
    owner: taozhang
    repo: blog-comments
    oauth:
        client_id: 355c956050e5f9bad9e5
        client_secret: 796d35bd9193ca8dffe9ce7e41fd707f3f615674
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: taozhang
    repo: blog-comments
        client_id: 355c956050e5f9bad9e5
        client_secret: 796d35bd9193ca8dffe9ce7e41fd707f3f615674
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
